const ADD_BASKET = 'ADD_BASKET';
const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET';
const EMPTY_BASKET = 'EMPTY_BASKET';
const SET_USER = 'SET_USER';

export default {
  ADD_BASKET,
  DELETE_FROM_BASKET,
  EMPTY_BASKET,
  SET_USER,
};
